---
version: '3'
services:

# START SERVICE metricbeat.overlay
  metricbeat:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.metricbeat.overlay:7.1.1
    environment: ['ES_METRICBEAT_OUTPUT_CONSOLE=${CONTECO_DC_METRICBEAT_OVERLAY_ENVIRONMENT_OUTPUT_CONSOLE}','ES_METRICBEAT_OUTPUT_ELASTICSEARCH=${CONTECO_DC_METRICBEAT_OVERLAY_ENVIRONMENT_OUTPUT_ELASTICSEARCH}','ES_METRICBEAT_OUTPUT_KAFKA=${CONTECO_DC_METRICBEAT_OVERLAY_ENVIRONMENT_OUTPUT_KAFKA}','ES_METRICBEAT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS=${CONTECO_DC_METRICBEAT_OVERLAY_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS}','ES_METRICBEAT_OUTPUT_CONFIG_KIBANA_HOST=${CONTECO_DC_METRICBEAT_OVERLAY_ENVIRONMENT_OUTPUT_CONFIG_KIBANA_HOST}','ES_METRICBEAT_OUTPUT_CONFIG_KIBANA_DASHBOARDS=${CONTECO_DC_METRICBEAT_OVERLAY_ENVIRONMENT_OUTPUT_CONFIG_KIBANA_DASHBOARDS}','ES_METRICBEAT_OUTPUT_CONFIG_KAFKA_HOSTS=${CONTECO_DC_METRICBEAT_OVERLAY_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_HOSTS}','ES_METRICBEAT_OUTPUT_CONFIG_KAFKA_TOPIC=${CONTECO_DC_METRICBEAT_OVERLAY_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_TOPIC}',${CONTECO_DC_METRICBEAT_OVERLAY_ENVIRONMENT_SERVICES}]
    command: []
    volumes: ['/etc:/hostfs/etc:ro']
    ports: []
    networks: [${CONTECO_TYPE}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_METRICBEAT_OVERLAY_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_METRICBEAT_OVERLAY_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_METRICBEAT_OVERLAY_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_METRICBEAT_OVERLAY_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: []
# END SERVICE metricbeat.overlay

volumes: {}
networks: {${CONTECO_TYPE}_overlay: { external: true }}
